{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plugin.trycatch",
    "module": "try-catch-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "try-catch-plugin-1.0.1.jar",
          "url": "try-catch-plugin-1.0.1.jar",
          "size": 10660,
          "sha512": "1ea123aede6f17101e8498598f314c4d41861ee576f46e40459c62bcdada75ef7c6bdb78ca8c6604c6acd04da094e8c52be38b0ad1f6e4bd52900e18a74cc696",
          "sha256": "0e1fb957609faa5c1f9e86c8dcb577dae3b3b6980a92c51e2be4dbc62b65e562",
          "sha1": "66094e21c990c5bd5b659e059343c567ba5e57d0",
          "md5": "fdba0668c8bf2fada7ec0ece83664544"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.quinn.hunter",
          "module": "hunter-transform",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "try-catch-plugin-1.0.1.jar",
          "url": "try-catch-plugin-1.0.1.jar",
          "size": 10660,
          "sha512": "1ea123aede6f17101e8498598f314c4d41861ee576f46e40459c62bcdada75ef7c6bdb78ca8c6604c6acd04da094e8c52be38b0ad1f6e4bd52900e18a74cc696",
          "sha256": "0e1fb957609faa5c1f9e86c8dcb577dae3b3b6980a92c51e2be4dbc62b65e562",
          "sha1": "66094e21c990c5bd5b659e059343c567ba5e57d0",
          "md5": "fdba0668c8bf2fada7ec0ece83664544"
        }
      ]
    }
  ]
}
