{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plugin.trycatch",
    "module": "try-catch-plugin",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "try-catch-plugin-1.0.1.jar",
          "url": "try-catch-plugin-1.0.1.jar",
          "size": 10721,
          "sha512": "f38bc7c5822a873f6c713bd4583c7825cf56f334efcc3c1d9db83e0754ed656f814eb3e009a12f61195a81866b2da5d5a076fd991337c59d761f502c147b0131",
          "sha256": "7931d3e444f3074e42a818b4249be3f3871449ac0b359db2e593730ee477f83f",
          "sha1": "3aad5c73d14f482f257a4b03dc8e913331227036",
          "md5": "51468462ddcd41ee31b149e405cf50d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "7.2"
          }
        },
        {
          "group": "com.quinn.hunter",
          "module": "hunter-transform",
          "version": {
            "requires": "0.9.3"
          },
          "excludes": [
            {
              "group": "com.android.tools.build",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "try-catch-plugin-1.0.1.jar",
          "url": "try-catch-plugin-1.0.1.jar",
          "size": 10721,
          "sha512": "f38bc7c5822a873f6c713bd4583c7825cf56f334efcc3c1d9db83e0754ed656f814eb3e009a12f61195a81866b2da5d5a076fd991337c59d761f502c147b0131",
          "sha256": "7931d3e444f3074e42a818b4249be3f3871449ac0b359db2e593730ee477f83f",
          "sha1": "3aad5c73d14f482f257a4b03dc8e913331227036",
          "md5": "51468462ddcd41ee31b149e405cf50d4"
        }
      ]
    }
  ]
}
