{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plugin.palladium",
    "module": "palladium",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "palladium-1.0.1.jar",
          "url": "palladium-1.0.1.jar",
          "size": 3687,
          "sha512": "f722d12d9433589beed181cab502026f70426762a6d48ec1839f9ff9cee9a8a45f0ca4a8e7c0cfa5bc147dcbdf1e7055b6a034c372daf965bb90da87825872a0",
          "sha256": "1a1a27b12fc7e632b0bd2feb49d194682e9cc2974571c27af6f3d20f127bbe8d",
          "sha1": "cce71d5de283f1574b1ee388a5d47cf1b6206bb0",
          "md5": "f03b797c1f3d0d3d1e108bd0287d84aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palladium-1.0.1.jar",
          "url": "palladium-1.0.1.jar",
          "size": 3687,
          "sha512": "f722d12d9433589beed181cab502026f70426762a6d48ec1839f9ff9cee9a8a45f0ca4a8e7c0cfa5bc147dcbdf1e7055b6a034c372daf965bb90da87825872a0",
          "sha256": "1a1a27b12fc7e632b0bd2feb49d194682e9cc2974571c27af6f3d20f127bbe8d",
          "sha1": "cce71d5de283f1574b1ee388a5d47cf1b6206bb0",
          "md5": "f03b797c1f3d0d3d1e108bd0287d84aa"
        }
      ]
    }
  ]
}
