{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plugin.palladium",
    "module": "palladium",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "palladium-1.0.1.jar",
          "url": "palladium-1.0.1.jar",
          "size": 3687,
          "sha512": "7f16e33392b46fea3d681aee762453c644bcc8e3389f288171ca1484da4bbf4ca27042716a7b4cf0210437f99c5a4c8a855a31f818b765bcfa140cbf361937d2",
          "sha256": "6b44f533c5d76c1cdd33fbdc4f5233adc591b4f7459656637472b2d9d03303b9",
          "sha1": "8d9f1fcea3d578bb8ab7b4d8d999b88f72f5921c",
          "md5": "fe6aece28154165a56dd5fa74aedbcb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "palladium-1.0.1.jar",
          "url": "palladium-1.0.1.jar",
          "size": 3687,
          "sha512": "7f16e33392b46fea3d681aee762453c644bcc8e3389f288171ca1484da4bbf4ca27042716a7b4cf0210437f99c5a4c8a855a31f818b765bcfa140cbf361937d2",
          "sha256": "6b44f533c5d76c1cdd33fbdc4f5233adc591b4f7459656637472b2d9d03303b9",
          "sha1": "8d9f1fcea3d578bb8ab7b4d8d999b88f72f5921c",
          "md5": "fe6aece28154165a56dd5fa74aedbcb4"
        }
      ]
    }
  ]
}
